name: Lint-And-Push-Artifact

on:
  push:
    branches: 
      - master

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    outputs:
      math_quiz: ${{ steps.filter.outputs.math_quiz }}
      parallell_downloader: ${{ steps.filter.outputs.parallell_downloader }}
      url_shortener: ${{ steps.filter.outputs.url_shortener }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            math_quiz:
              - 'math_quiz/**'
            parallell_downloader:
              - 'parallell_downloader/**'
            url_shortener:
              - 'url_shortener/**'
  push-artifact:
    name: Push artifacts
    needs: super-lint
    if: ${{ needs.super-lint.outputs.url_shortener == 'true' }} || ${{ needs.super-lint.outputs.parallell_downloader == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.7' # The Go version to download (if necessary) and use.
      - name: Set up JFrog
        uses: jfrog/setup-jfrog-cli@v1
        # See for instructions to make secret https://circleci.com/docs/2.0/artifactory/
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD
      - name: Build url_shortener app
        if: ${{ needs.super-lint.outputs.url_shortener == 'true' }}
        run: |
          cd url_shortener
          go build .
      - name: Push url_shortener to artifactory
        if: ${{ needs.super-lint.outputs.url_shortener == 'true' }}
        env:
          DATE: "${{ steps.current-time.outputs.formattedTime }}"
        run: |
          cd url_shortener
          jfrog rt u "url_shortener" go --build-name="${DATE}_url_shortener" --build-number=$GITHUB_RUN_NUMBER --flat=false
      - name: Build parallell_downloader app
        if: ${{ needs.super-lint.outputs.parallell_downloader == 'true' }}
        run: |
          cd parallell_downloader
          go build .
      - name: Push parallell_downloader to artifactory
        if: ${{ needs.super-lint.outputs.parallell_downloader == 'true' }}
        env:
          DATE: "${{ steps.current-time.outputs.formattedTime }}"
        run: |
          cd parallell_downloader
          jfrog rt u "parallell_downloader" go --build-name="${DATE}parallell_downloader" --build-number=$GITHUB_RUN_NUMBER --flat=false